//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_Central.PessoaWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PessoaS", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class PessoaS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Bi {
            get {
                return this.BiField;
            }
            set {
                if ((this.BiField.Equals(value) != true)) {
                    this.BiField = value;
                    this.RaisePropertyChanged("Bi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Idade {
            get {
                return this.IdadeField;
            }
            set {
                if ((this.IdadeField.Equals(value) != true)) {
                    this.IdadeField = value;
                    this.RaisePropertyChanged("Idade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localidade {
            get {
                return this.LocalidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalidadeField, value) != true)) {
                    this.LocalidadeField = value;
                    this.RaisePropertyChanged("Localidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventoS2", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class EventoS2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CapacidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalizacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LotacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Capacidade {
            get {
                return this.CapacidadeField;
            }
            set {
                if ((this.CapacidadeField.Equals(value) != true)) {
                    this.CapacidadeField = value;
                    this.RaisePropertyChanged("Capacidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Localizacao {
            get {
                return this.LocalizacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalizacaoField, value) != true)) {
                    this.LocalizacaoField = value;
                    this.RaisePropertyChanged("Localizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Lotacao {
            get {
                return this.LotacaoField;
            }
            set {
                if ((this.LotacaoField.Equals(value) != true)) {
                    this.LotacaoField = value;
                    this.RaisePropertyChanged("Lotacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PessoaWS.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetData", ReplyAction="http://tempuri.org/IService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        WS_Central.PessoaWS.CompositeType GetDataUsingDataContract(WS_Central.PessoaWS.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WS_Central.PessoaWS.CompositeType> GetDataUsingDataContractAsync(WS_Central.PessoaWS.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CheckLogin", ReplyAction="http://tempuri.org/IService/CheckLoginResponse")]
        WS_Central.PessoaWS.PessoaS CheckLogin(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CheckLogin", ReplyAction="http://tempuri.org/IService/CheckLoginResponse")]
        System.Threading.Tasks.Task<WS_Central.PessoaWS.PessoaS> CheckLoginAsync(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CheckRegisto", ReplyAction="http://tempuri.org/IService/CheckRegistoResponse")]
        string CheckRegisto(string user, string password, string nome, string localidade, int idade, int bi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CheckRegisto", ReplyAction="http://tempuri.org/IService/CheckRegistoResponse")]
        System.Threading.Tasks.Task<string> CheckRegistoAsync(string user, string password, string nome, string localidade, int idade, int bi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EfetuaReserva", ReplyAction="http://tempuri.org/IService/EfetuaReservaResponse")]
        string EfetuaReserva(int userid, int eventid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EfetuaReserva", ReplyAction="http://tempuri.org/IService/EfetuaReservaResponse")]
        System.Threading.Tasks.Task<string> EfetuaReservaAsync(int userid, int eventid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RemoveReserva", ReplyAction="http://tempuri.org/IService/RemoveReservaResponse")]
        string RemoveReserva(int userid, int eventid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RemoveReserva", ReplyAction="http://tempuri.org/IService/RemoveReservaResponse")]
        System.Threading.Tasks.Task<string> RemoveReservaAsync(int userid, int eventid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ExisteReserva", ReplyAction="http://tempuri.org/IService/ExisteReservaResponse")]
        string ExisteReserva(WS_Central.PessoaWS.PessoaS user, WS_Central.PessoaWS.EventoS2 evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ExisteReserva", ReplyAction="http://tempuri.org/IService/ExisteReservaResponse")]
        System.Threading.Tasks.Task<string> ExisteReservaAsync(WS_Central.PessoaWS.PessoaS user, WS_Central.PessoaWS.EventoS2 evento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminaPessoa", ReplyAction="http://tempuri.org/IService/EliminaPessoaResponse")]
        string EliminaPessoa(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/EliminaPessoa", ReplyAction="http://tempuri.org/IService/EliminaPessoaResponse")]
        System.Threading.Tasks.Task<string> EliminaPessoaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllUsers", ReplyAction="http://tempuri.org/IService/GetAllUsersResponse")]
        WS_Central.PessoaWS.PessoaS[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllUsers", ReplyAction="http://tempuri.org/IService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<WS_Central.PessoaWS.PessoaS[]> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPessoa", ReplyAction="http://tempuri.org/IService/GetPessoaResponse")]
        WS_Central.PessoaWS.PessoaS GetPessoa(int id, string username, string nome, int tipo, int idade, string localidade, int ident);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPessoa", ReplyAction="http://tempuri.org/IService/GetPessoaResponse")]
        System.Threading.Tasks.Task<WS_Central.PessoaWS.PessoaS> GetPessoaAsync(int id, string username, string nome, int tipo, int idade, string localidade, int ident);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : WS_Central.PessoaWS.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WS_Central.PessoaWS.IService>, WS_Central.PessoaWS.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WS_Central.PessoaWS.CompositeType GetDataUsingDataContract(WS_Central.PessoaWS.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WS_Central.PessoaWS.CompositeType> GetDataUsingDataContractAsync(WS_Central.PessoaWS.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public WS_Central.PessoaWS.PessoaS CheckLogin(string user, string password) {
            return base.Channel.CheckLogin(user, password);
        }
        
        public System.Threading.Tasks.Task<WS_Central.PessoaWS.PessoaS> CheckLoginAsync(string user, string password) {
            return base.Channel.CheckLoginAsync(user, password);
        }
        
        public string CheckRegisto(string user, string password, string nome, string localidade, int idade, int bi) {
            return base.Channel.CheckRegisto(user, password, nome, localidade, idade, bi);
        }
        
        public System.Threading.Tasks.Task<string> CheckRegistoAsync(string user, string password, string nome, string localidade, int idade, int bi) {
            return base.Channel.CheckRegistoAsync(user, password, nome, localidade, idade, bi);
        }
        
        public string EfetuaReserva(int userid, int eventid) {
            return base.Channel.EfetuaReserva(userid, eventid);
        }
        
        public System.Threading.Tasks.Task<string> EfetuaReservaAsync(int userid, int eventid) {
            return base.Channel.EfetuaReservaAsync(userid, eventid);
        }
        
        public string RemoveReserva(int userid, int eventid) {
            return base.Channel.RemoveReserva(userid, eventid);
        }
        
        public System.Threading.Tasks.Task<string> RemoveReservaAsync(int userid, int eventid) {
            return base.Channel.RemoveReservaAsync(userid, eventid);
        }
        
        public string ExisteReserva(WS_Central.PessoaWS.PessoaS user, WS_Central.PessoaWS.EventoS2 evento) {
            return base.Channel.ExisteReserva(user, evento);
        }
        
        public System.Threading.Tasks.Task<string> ExisteReservaAsync(WS_Central.PessoaWS.PessoaS user, WS_Central.PessoaWS.EventoS2 evento) {
            return base.Channel.ExisteReservaAsync(user, evento);
        }
        
        public string EliminaPessoa(int id) {
            return base.Channel.EliminaPessoa(id);
        }
        
        public System.Threading.Tasks.Task<string> EliminaPessoaAsync(int id) {
            return base.Channel.EliminaPessoaAsync(id);
        }
        
        public WS_Central.PessoaWS.PessoaS[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<WS_Central.PessoaWS.PessoaS[]> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public WS_Central.PessoaWS.PessoaS GetPessoa(int id, string username, string nome, int tipo, int idade, string localidade, int ident) {
            return base.Channel.GetPessoa(id, username, nome, tipo, idade, localidade, ident);
        }
        
        public System.Threading.Tasks.Task<WS_Central.PessoaWS.PessoaS> GetPessoaAsync(int id, string username, string nome, int tipo, int idade, string localidade, int ident) {
            return base.Channel.GetPessoaAsync(id, username, nome, tipo, idade, localidade, ident);
        }
    }
}
