//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServicoCentralWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PessoaS", Namespace="http://temp123.pt")]
    [System.SerializableAttribute()]
    public partial class PessoaS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServicoCentralWS.ExtensionDataObject ExtensionData1Field;
        
        private int BiField;
        
        private int IdField;
        
        private int IdadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        private int TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public WindowsFormsApp1.ServicoCentralWS.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Bi {
            get {
                return this.BiField;
            }
            set {
                if ((this.BiField.Equals(value) != true)) {
                    this.BiField = value;
                    this.RaisePropertyChanged("Bi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Idade {
            get {
                return this.IdadeField;
            }
            set {
                if ((this.IdadeField.Equals(value) != true)) {
                    this.IdadeField = value;
                    this.RaisePropertyChanged("Idade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Localidade {
            get {
                return this.LocalidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalidadeField, value) != true)) {
                    this.LocalidadeField = value;
                    this.RaisePropertyChanged("Localidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtensionDataObject", Namespace="http://temp123.pt")]
    [System.SerializableAttribute()]
    public partial class ExtensionDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventoS2", Namespace="http://temp123.pt")]
    [System.SerializableAttribute()]
    public partial class EventoS2 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServicoCentralWS.ExtensionDataObject ExtensionData1Field;
        
        private int CapacidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalizacaoField;
        
        private int LotacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public WindowsFormsApp1.ServicoCentralWS.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Capacidade {
            get {
                return this.CapacidadeField;
            }
            set {
                if ((this.CapacidadeField.Equals(value) != true)) {
                    this.CapacidadeField = value;
                    this.RaisePropertyChanged("Capacidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Localizacao {
            get {
                return this.LocalizacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalizacaoField, value) != true)) {
                    this.LocalizacaoField = value;
                    this.RaisePropertyChanged("Localizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Lotacao {
            get {
                return this.LotacaoField;
            }
            set {
                if ((this.LotacaoField.Equals(value) != true)) {
                    this.LotacaoField = value;
                    this.RaisePropertyChanged("Lotacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventoS", Namespace="http://temp123.pt")]
    [System.SerializableAttribute()]
    public partial class EventoS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WindowsFormsApp1.ServicoCentralWS.ExtensionDataObject ExtensionData1Field;
        
        private int CapacidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalizacaoField;
        
        private int LotacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public WindowsFormsApp1.ServicoCentralWS.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Capacidade {
            get {
                return this.CapacidadeField;
            }
            set {
                if ((this.CapacidadeField.Equals(value) != true)) {
                    this.CapacidadeField = value;
                    this.RaisePropertyChanged("Capacidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Localizacao {
            get {
                return this.LocalizacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalizacaoField, value) != true)) {
                    this.LocalizacaoField = value;
                    this.RaisePropertyChanged("Localizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Lotacao {
            get {
                return this.LotacaoField;
            }
            set {
                if ((this.LotacaoField.Equals(value) != true)) {
                    this.LotacaoField = value;
                    this.RaisePropertyChanged("Lotacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://temp123.pt", ConfigurationName="ServicoCentralWS.CentralServicoSoap")]
    public interface CentralServicoSoap {
        
        // CODEGEN: Generating message contract since element name user from namespace http://temp123.pt is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResultadoLogin", ReplyAction="*")]
        WindowsFormsApp1.ServicoCentralWS.ResultadoLoginResponse ResultadoLogin(WindowsFormsApp1.ServicoCentralWS.ResultadoLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResultadoLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResultadoLoginResponse> ResultadoLoginAsync(WindowsFormsApp1.ServicoCentralWS.ResultadoLoginRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://temp123.pt is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResultadoRegisto", ReplyAction="*")]
        WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoResponse ResultadoRegisto(WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResultadoRegisto", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoResponse> ResultadoRegistoAsync(WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoRequest request);
        
        // CODEGEN: Generating message contract since element name ResEfetuaReservaResult from namespace http://temp123.pt is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResEfetuaReserva", ReplyAction="*")]
        WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaResponse ResEfetuaReserva(WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResEfetuaReserva", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaResponse> ResEfetuaReservaAsync(WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaRequest request);
        
        // CODEGEN: Generating message contract since element name ResRemoveReservaResult from namespace http://temp123.pt is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResRemoveReserva", ReplyAction="*")]
        WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaResponse ResRemoveReserva(WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResRemoveReserva", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaResponse> ResRemoveReservaAsync(WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaRequest request);
        
        // CODEGEN: Generating message contract since element name ResEliminaPessoaResult from namespace http://temp123.pt is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResEliminaPessoa", ReplyAction="*")]
        WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaResponse ResEliminaPessoa(WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResEliminaPessoa", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaResponse> ResEliminaPessoaAsync(WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaRequest request);
        
        // CODEGEN: Generating message contract since element name ResListaPessoasResult from namespace http://temp123.pt is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResListaPessoas", ReplyAction="*")]
        WindowsFormsApp1.ServicoCentralWS.ResListaPessoasResponse ResListaPessoas(WindowsFormsApp1.ServicoCentralWS.ResListaPessoasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResListaPessoas", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResListaPessoasResponse> ResListaPessoasAsync(WindowsFormsApp1.ServicoCentralWS.ResListaPessoasRequest request);
        
        // CODEGEN: Generating message contract since element name pessoa from namespace http://temp123.pt is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResExisteReserva", ReplyAction="*")]
        WindowsFormsApp1.ServicoCentralWS.ResExisteReservaResponse ResExisteReserva(WindowsFormsApp1.ServicoCentralWS.ResExisteReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResExisteReserva", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResExisteReservaResponse> ResExisteReservaAsync(WindowsFormsApp1.ServicoCentralWS.ResExisteReservaRequest request);
        
        // CODEGEN: Generating message contract since element name nome from namespace http://temp123.pt is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResCriarEvento", ReplyAction="*")]
        WindowsFormsApp1.ServicoCentralWS.ResCriarEventoResponse ResCriarEvento(WindowsFormsApp1.ServicoCentralWS.ResCriarEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResCriarEvento", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResCriarEventoResponse> ResCriarEventoAsync(WindowsFormsApp1.ServicoCentralWS.ResCriarEventoRequest request);
        
        // CODEGEN: Generating message contract since element name ResEliminaEventoResult from namespace http://temp123.pt is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResEliminaEvento", ReplyAction="*")]
        WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoResponse ResEliminaEvento(WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResEliminaEvento", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoResponse> ResEliminaEventoAsync(WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoRequest request);
        
        // CODEGEN: Generating message contract since element name ResListaEventosResult from namespace http://temp123.pt is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResListaEventos", ReplyAction="*")]
        WindowsFormsApp1.ServicoCentralWS.ResListaEventosResponse ResListaEventos(WindowsFormsApp1.ServicoCentralWS.ResListaEventosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResListaEventos", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResListaEventosResponse> ResListaEventosAsync(WindowsFormsApp1.ServicoCentralWS.ResListaEventosRequest request);
        
        // CODEGEN: Generating message contract since element name nome from namespace http://temp123.pt is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResEscolherEvento", ReplyAction="*")]
        WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoResponse ResEscolherEvento(WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://temp123.pt/ResEscolherEvento", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoResponse> ResEscolherEventoAsync(WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResultadoLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResultadoLogin", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResultadoLoginRequestBody Body;
        
        public ResultadoLoginRequest() {
        }
        
        public ResultadoLoginRequest(WindowsFormsApp1.ServicoCentralWS.ResultadoLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResultadoLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public ResultadoLoginRequestBody() {
        }
        
        public ResultadoLoginRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResultadoLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResultadoLoginResponse", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResultadoLoginResponseBody Body;
        
        public ResultadoLoginResponse() {
        }
        
        public ResultadoLoginResponse(WindowsFormsApp1.ServicoCentralWS.ResultadoLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResultadoLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.PessoaS ResultadoLoginResult;
        
        public ResultadoLoginResponseBody() {
        }
        
        public ResultadoLoginResponseBody(WindowsFormsApp1.ServicoCentralWS.PessoaS ResultadoLoginResult) {
            this.ResultadoLoginResult = ResultadoLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResultadoRegistoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResultadoRegisto", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoRequestBody Body;
        
        public ResultadoRegistoRequest() {
        }
        
        public ResultadoRegistoRequest(WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResultadoRegistoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string localidade;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int idade;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int bi;
        
        public ResultadoRegistoRequestBody() {
        }
        
        public ResultadoRegistoRequestBody(string user, string pass, string nome, string localidade, int idade, int bi) {
            this.user = user;
            this.pass = pass;
            this.nome = nome;
            this.localidade = localidade;
            this.idade = idade;
            this.bi = bi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResultadoRegistoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResultadoRegistoResponse", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoResponseBody Body;
        
        public ResultadoRegistoResponse() {
        }
        
        public ResultadoRegistoResponse(WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResultadoRegistoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResultadoRegistoResult;
        
        public ResultadoRegistoResponseBody() {
        }
        
        public ResultadoRegistoResponseBody(string ResultadoRegistoResult) {
            this.ResultadoRegistoResult = ResultadoRegistoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResEfetuaReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResEfetuaReserva", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaRequestBody Body;
        
        public ResEfetuaReservaRequest() {
        }
        
        public ResEfetuaReservaRequest(WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResEfetuaReservaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int eventid;
        
        public ResEfetuaReservaRequestBody() {
        }
        
        public ResEfetuaReservaRequestBody(int userid, int eventid) {
            this.userid = userid;
            this.eventid = eventid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResEfetuaReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResEfetuaReservaResponse", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaResponseBody Body;
        
        public ResEfetuaReservaResponse() {
        }
        
        public ResEfetuaReservaResponse(WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResEfetuaReservaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResEfetuaReservaResult;
        
        public ResEfetuaReservaResponseBody() {
        }
        
        public ResEfetuaReservaResponseBody(string ResEfetuaReservaResult) {
            this.ResEfetuaReservaResult = ResEfetuaReservaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResRemoveReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResRemoveReserva", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaRequestBody Body;
        
        public ResRemoveReservaRequest() {
        }
        
        public ResRemoveReservaRequest(WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResRemoveReservaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int eventid;
        
        public ResRemoveReservaRequestBody() {
        }
        
        public ResRemoveReservaRequestBody(int userid, int eventid) {
            this.userid = userid;
            this.eventid = eventid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResRemoveReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResRemoveReservaResponse", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaResponseBody Body;
        
        public ResRemoveReservaResponse() {
        }
        
        public ResRemoveReservaResponse(WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResRemoveReservaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResRemoveReservaResult;
        
        public ResRemoveReservaResponseBody() {
        }
        
        public ResRemoveReservaResponseBody(string ResRemoveReservaResult) {
            this.ResRemoveReservaResult = ResRemoveReservaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResEliminaPessoaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResEliminaPessoa", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaRequestBody Body;
        
        public ResEliminaPessoaRequest() {
        }
        
        public ResEliminaPessoaRequest(WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResEliminaPessoaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ResEliminaPessoaRequestBody() {
        }
        
        public ResEliminaPessoaRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResEliminaPessoaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResEliminaPessoaResponse", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaResponseBody Body;
        
        public ResEliminaPessoaResponse() {
        }
        
        public ResEliminaPessoaResponse(WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResEliminaPessoaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResEliminaPessoaResult;
        
        public ResEliminaPessoaResponseBody() {
        }
        
        public ResEliminaPessoaResponseBody(string ResEliminaPessoaResult) {
            this.ResEliminaPessoaResult = ResEliminaPessoaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResListaPessoasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResListaPessoas", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResListaPessoasRequestBody Body;
        
        public ResListaPessoasRequest() {
        }
        
        public ResListaPessoasRequest(WindowsFormsApp1.ServicoCentralWS.ResListaPessoasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ResListaPessoasRequestBody {
        
        public ResListaPessoasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResListaPessoasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResListaPessoasResponse", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResListaPessoasResponseBody Body;
        
        public ResListaPessoasResponse() {
        }
        
        public ResListaPessoasResponse(WindowsFormsApp1.ServicoCentralWS.ResListaPessoasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResListaPessoasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.PessoaS[] ResListaPessoasResult;
        
        public ResListaPessoasResponseBody() {
        }
        
        public ResListaPessoasResponseBody(WindowsFormsApp1.ServicoCentralWS.PessoaS[] ResListaPessoasResult) {
            this.ResListaPessoasResult = ResListaPessoasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResExisteReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResExisteReserva", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResExisteReservaRequestBody Body;
        
        public ResExisteReservaRequest() {
        }
        
        public ResExisteReservaRequest(WindowsFormsApp1.ServicoCentralWS.ResExisteReservaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResExisteReservaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.PessoaS pessoa;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WindowsFormsApp1.ServicoCentralWS.EventoS2 evento;
        
        public ResExisteReservaRequestBody() {
        }
        
        public ResExisteReservaRequestBody(WindowsFormsApp1.ServicoCentralWS.PessoaS pessoa, WindowsFormsApp1.ServicoCentralWS.EventoS2 evento) {
            this.pessoa = pessoa;
            this.evento = evento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResExisteReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResExisteReservaResponse", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResExisteReservaResponseBody Body;
        
        public ResExisteReservaResponse() {
        }
        
        public ResExisteReservaResponse(WindowsFormsApp1.ServicoCentralWS.ResExisteReservaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResExisteReservaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResExisteReservaResult;
        
        public ResExisteReservaResponseBody() {
        }
        
        public ResExisteReservaResponseBody(string ResExisteReservaResult) {
            this.ResExisteReservaResult = ResExisteReservaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResCriarEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResCriarEvento", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResCriarEventoRequestBody Body;
        
        public ResCriarEventoRequest() {
        }
        
        public ResCriarEventoRequest(WindowsFormsApp1.ServicoCentralWS.ResCriarEventoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResCriarEventoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string data;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string local;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int lotacao;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int capacidade;
        
        public ResCriarEventoRequestBody() {
        }
        
        public ResCriarEventoRequestBody(string nome, string data, string local, int lotacao, int capacidade) {
            this.nome = nome;
            this.data = data;
            this.local = local;
            this.lotacao = lotacao;
            this.capacidade = capacidade;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResCriarEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResCriarEventoResponse", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResCriarEventoResponseBody Body;
        
        public ResCriarEventoResponse() {
        }
        
        public ResCriarEventoResponse(WindowsFormsApp1.ServicoCentralWS.ResCriarEventoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResCriarEventoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResCriarEventoResult;
        
        public ResCriarEventoResponseBody() {
        }
        
        public ResCriarEventoResponseBody(string ResCriarEventoResult) {
            this.ResCriarEventoResult = ResCriarEventoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResEliminaEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResEliminaEvento", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoRequestBody Body;
        
        public ResEliminaEventoRequest() {
        }
        
        public ResEliminaEventoRequest(WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResEliminaEventoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ResEliminaEventoRequestBody() {
        }
        
        public ResEliminaEventoRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResEliminaEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResEliminaEventoResponse", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoResponseBody Body;
        
        public ResEliminaEventoResponse() {
        }
        
        public ResEliminaEventoResponse(WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResEliminaEventoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResEliminaEventoResult;
        
        public ResEliminaEventoResponseBody() {
        }
        
        public ResEliminaEventoResponseBody(string ResEliminaEventoResult) {
            this.ResEliminaEventoResult = ResEliminaEventoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResListaEventosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResListaEventos", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResListaEventosRequestBody Body;
        
        public ResListaEventosRequest() {
        }
        
        public ResListaEventosRequest(WindowsFormsApp1.ServicoCentralWS.ResListaEventosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ResListaEventosRequestBody {
        
        public ResListaEventosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResListaEventosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResListaEventosResponse", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResListaEventosResponseBody Body;
        
        public ResListaEventosResponse() {
        }
        
        public ResListaEventosResponse(WindowsFormsApp1.ServicoCentralWS.ResListaEventosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResListaEventosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.EventoS[] ResListaEventosResult;
        
        public ResListaEventosResponseBody() {
        }
        
        public ResListaEventosResponseBody(WindowsFormsApp1.ServicoCentralWS.EventoS[] ResListaEventosResult) {
            this.ResListaEventosResult = ResListaEventosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResEscolherEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResEscolherEvento", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoRequestBody Body;
        
        public ResEscolherEventoRequest() {
        }
        
        public ResEscolherEventoRequest(WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResEscolherEventoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nome;
        
        public ResEscolherEventoRequestBody() {
        }
        
        public ResEscolherEventoRequestBody(string nome) {
            this.nome = nome;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResEscolherEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResEscolherEventoResponse", Namespace="http://temp123.pt", Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoResponseBody Body;
        
        public ResEscolherEventoResponse() {
        }
        
        public ResEscolherEventoResponse(WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://temp123.pt")]
    public partial class ResEscolherEventoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp1.ServicoCentralWS.EventoS ResEscolherEventoResult;
        
        public ResEscolherEventoResponseBody() {
        }
        
        public ResEscolherEventoResponseBody(WindowsFormsApp1.ServicoCentralWS.EventoS ResEscolherEventoResult) {
            this.ResEscolherEventoResult = ResEscolherEventoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CentralServicoSoapChannel : WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CentralServicoSoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap>, WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap {
        
        public CentralServicoSoapClient() {
        }
        
        public CentralServicoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CentralServicoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CentralServicoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CentralServicoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServicoCentralWS.ResultadoLoginResponse WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResultadoLogin(WindowsFormsApp1.ServicoCentralWS.ResultadoLoginRequest request) {
            return base.Channel.ResultadoLogin(request);
        }
        
        public WindowsFormsApp1.ServicoCentralWS.PessoaS ResultadoLogin(string user, string pass) {
            WindowsFormsApp1.ServicoCentralWS.ResultadoLoginRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResultadoLoginRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResultadoLoginRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            WindowsFormsApp1.ServicoCentralWS.ResultadoLoginResponse retVal = ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResultadoLogin(inValue);
            return retVal.Body.ResultadoLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResultadoLoginResponse> WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResultadoLoginAsync(WindowsFormsApp1.ServicoCentralWS.ResultadoLoginRequest request) {
            return base.Channel.ResultadoLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResultadoLoginResponse> ResultadoLoginAsync(string user, string pass) {
            WindowsFormsApp1.ServicoCentralWS.ResultadoLoginRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResultadoLoginRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResultadoLoginRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResultadoLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoResponse WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResultadoRegisto(WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoRequest request) {
            return base.Channel.ResultadoRegisto(request);
        }
        
        public string ResultadoRegisto(string user, string pass, string nome, string localidade, int idade, int bi) {
            WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.nome = nome;
            inValue.Body.localidade = localidade;
            inValue.Body.idade = idade;
            inValue.Body.bi = bi;
            WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoResponse retVal = ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResultadoRegisto(inValue);
            return retVal.Body.ResultadoRegistoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoResponse> WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResultadoRegistoAsync(WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoRequest request) {
            return base.Channel.ResultadoRegistoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoResponse> ResultadoRegistoAsync(string user, string pass, string nome, string localidade, int idade, int bi) {
            WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResultadoRegistoRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            inValue.Body.nome = nome;
            inValue.Body.localidade = localidade;
            inValue.Body.idade = idade;
            inValue.Body.bi = bi;
            return ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResultadoRegistoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaResponse WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResEfetuaReserva(WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaRequest request) {
            return base.Channel.ResEfetuaReserva(request);
        }
        
        public string ResEfetuaReserva(int userid, int eventid) {
            WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaRequestBody();
            inValue.Body.userid = userid;
            inValue.Body.eventid = eventid;
            WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaResponse retVal = ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResEfetuaReserva(inValue);
            return retVal.Body.ResEfetuaReservaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaResponse> WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResEfetuaReservaAsync(WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaRequest request) {
            return base.Channel.ResEfetuaReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaResponse> ResEfetuaReservaAsync(int userid, int eventid) {
            WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResEfetuaReservaRequestBody();
            inValue.Body.userid = userid;
            inValue.Body.eventid = eventid;
            return ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResEfetuaReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaResponse WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResRemoveReserva(WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaRequest request) {
            return base.Channel.ResRemoveReserva(request);
        }
        
        public string ResRemoveReserva(int userid, int eventid) {
            WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaRequestBody();
            inValue.Body.userid = userid;
            inValue.Body.eventid = eventid;
            WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaResponse retVal = ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResRemoveReserva(inValue);
            return retVal.Body.ResRemoveReservaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaResponse> WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResRemoveReservaAsync(WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaRequest request) {
            return base.Channel.ResRemoveReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaResponse> ResRemoveReservaAsync(int userid, int eventid) {
            WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResRemoveReservaRequestBody();
            inValue.Body.userid = userid;
            inValue.Body.eventid = eventid;
            return ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResRemoveReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaResponse WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResEliminaPessoa(WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaRequest request) {
            return base.Channel.ResEliminaPessoa(request);
        }
        
        public string ResEliminaPessoa(int id) {
            WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaRequestBody();
            inValue.Body.id = id;
            WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaResponse retVal = ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResEliminaPessoa(inValue);
            return retVal.Body.ResEliminaPessoaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaResponse> WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResEliminaPessoaAsync(WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaRequest request) {
            return base.Channel.ResEliminaPessoaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaResponse> ResEliminaPessoaAsync(int id) {
            WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResEliminaPessoaRequestBody();
            inValue.Body.id = id;
            return ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResEliminaPessoaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServicoCentralWS.ResListaPessoasResponse WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResListaPessoas(WindowsFormsApp1.ServicoCentralWS.ResListaPessoasRequest request) {
            return base.Channel.ResListaPessoas(request);
        }
        
        public WindowsFormsApp1.ServicoCentralWS.PessoaS[] ResListaPessoas() {
            WindowsFormsApp1.ServicoCentralWS.ResListaPessoasRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResListaPessoasRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResListaPessoasRequestBody();
            WindowsFormsApp1.ServicoCentralWS.ResListaPessoasResponse retVal = ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResListaPessoas(inValue);
            return retVal.Body.ResListaPessoasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResListaPessoasResponse> WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResListaPessoasAsync(WindowsFormsApp1.ServicoCentralWS.ResListaPessoasRequest request) {
            return base.Channel.ResListaPessoasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResListaPessoasResponse> ResListaPessoasAsync() {
            WindowsFormsApp1.ServicoCentralWS.ResListaPessoasRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResListaPessoasRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResListaPessoasRequestBody();
            return ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResListaPessoasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServicoCentralWS.ResExisteReservaResponse WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResExisteReserva(WindowsFormsApp1.ServicoCentralWS.ResExisteReservaRequest request) {
            return base.Channel.ResExisteReserva(request);
        }
        
        public string ResExisteReserva(WindowsFormsApp1.ServicoCentralWS.PessoaS pessoa, WindowsFormsApp1.ServicoCentralWS.EventoS2 evento) {
            WindowsFormsApp1.ServicoCentralWS.ResExisteReservaRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResExisteReservaRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResExisteReservaRequestBody();
            inValue.Body.pessoa = pessoa;
            inValue.Body.evento = evento;
            WindowsFormsApp1.ServicoCentralWS.ResExisteReservaResponse retVal = ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResExisteReserva(inValue);
            return retVal.Body.ResExisteReservaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResExisteReservaResponse> WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResExisteReservaAsync(WindowsFormsApp1.ServicoCentralWS.ResExisteReservaRequest request) {
            return base.Channel.ResExisteReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResExisteReservaResponse> ResExisteReservaAsync(WindowsFormsApp1.ServicoCentralWS.PessoaS pessoa, WindowsFormsApp1.ServicoCentralWS.EventoS2 evento) {
            WindowsFormsApp1.ServicoCentralWS.ResExisteReservaRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResExisteReservaRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResExisteReservaRequestBody();
            inValue.Body.pessoa = pessoa;
            inValue.Body.evento = evento;
            return ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResExisteReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServicoCentralWS.ResCriarEventoResponse WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResCriarEvento(WindowsFormsApp1.ServicoCentralWS.ResCriarEventoRequest request) {
            return base.Channel.ResCriarEvento(request);
        }
        
        public string ResCriarEvento(string nome, string data, string local, int lotacao, int capacidade) {
            WindowsFormsApp1.ServicoCentralWS.ResCriarEventoRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResCriarEventoRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResCriarEventoRequestBody();
            inValue.Body.nome = nome;
            inValue.Body.data = data;
            inValue.Body.local = local;
            inValue.Body.lotacao = lotacao;
            inValue.Body.capacidade = capacidade;
            WindowsFormsApp1.ServicoCentralWS.ResCriarEventoResponse retVal = ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResCriarEvento(inValue);
            return retVal.Body.ResCriarEventoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResCriarEventoResponse> WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResCriarEventoAsync(WindowsFormsApp1.ServicoCentralWS.ResCriarEventoRequest request) {
            return base.Channel.ResCriarEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResCriarEventoResponse> ResCriarEventoAsync(string nome, string data, string local, int lotacao, int capacidade) {
            WindowsFormsApp1.ServicoCentralWS.ResCriarEventoRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResCriarEventoRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResCriarEventoRequestBody();
            inValue.Body.nome = nome;
            inValue.Body.data = data;
            inValue.Body.local = local;
            inValue.Body.lotacao = lotacao;
            inValue.Body.capacidade = capacidade;
            return ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResCriarEventoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoResponse WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResEliminaEvento(WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoRequest request) {
            return base.Channel.ResEliminaEvento(request);
        }
        
        public string ResEliminaEvento(int id) {
            WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoRequestBody();
            inValue.Body.id = id;
            WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoResponse retVal = ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResEliminaEvento(inValue);
            return retVal.Body.ResEliminaEventoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoResponse> WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResEliminaEventoAsync(WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoRequest request) {
            return base.Channel.ResEliminaEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoResponse> ResEliminaEventoAsync(int id) {
            WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResEliminaEventoRequestBody();
            inValue.Body.id = id;
            return ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResEliminaEventoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServicoCentralWS.ResListaEventosResponse WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResListaEventos(WindowsFormsApp1.ServicoCentralWS.ResListaEventosRequest request) {
            return base.Channel.ResListaEventos(request);
        }
        
        public WindowsFormsApp1.ServicoCentralWS.EventoS[] ResListaEventos() {
            WindowsFormsApp1.ServicoCentralWS.ResListaEventosRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResListaEventosRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResListaEventosRequestBody();
            WindowsFormsApp1.ServicoCentralWS.ResListaEventosResponse retVal = ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResListaEventos(inValue);
            return retVal.Body.ResListaEventosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResListaEventosResponse> WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResListaEventosAsync(WindowsFormsApp1.ServicoCentralWS.ResListaEventosRequest request) {
            return base.Channel.ResListaEventosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResListaEventosResponse> ResListaEventosAsync() {
            WindowsFormsApp1.ServicoCentralWS.ResListaEventosRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResListaEventosRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResListaEventosRequestBody();
            return ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResListaEventosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoResponse WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResEscolherEvento(WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoRequest request) {
            return base.Channel.ResEscolherEvento(request);
        }
        
        public WindowsFormsApp1.ServicoCentralWS.EventoS ResEscolherEvento(string nome) {
            WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoRequestBody();
            inValue.Body.nome = nome;
            WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoResponse retVal = ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResEscolherEvento(inValue);
            return retVal.Body.ResEscolherEventoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoResponse> WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap.ResEscolherEventoAsync(WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoRequest request) {
            return base.Channel.ResEscolherEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoResponse> ResEscolherEventoAsync(string nome) {
            WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoRequest inValue = new WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoRequest();
            inValue.Body = new WindowsFormsApp1.ServicoCentralWS.ResEscolherEventoRequestBody();
            inValue.Body.nome = nome;
            return ((WindowsFormsApp1.ServicoCentralWS.CentralServicoSoap)(this)).ResEscolherEventoAsync(inValue);
        }
    }
}
